<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-04T19:49:07 IST" name="Default suite" finished-at="2024-02-04T19:55:02 IST" duration-ms="355355">
    <groups>
    </groups>
    <test started-at="2024-02-04T19:49:07 IST" name="Default test" finished-at="2024-02-04T19:55:02 IST" duration-ms="355355">
      <class name="TestCases.LoginTest">
        <test-method is-config="true" signature="loadConfigProp()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:49:07 IST" name="loadConfigProp" finished-at="2024-02-04T19:49:07 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfigProp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:49:07 IST" name="setUp" finished-at="2024-02-04T19:49:16 IST" duration-ms="9358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TC01_Bathroom_Cleaning_Flow()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:49:16 IST" name="TC01_Bathroom_Cleaning_Flow" finished-at="2024-02-04T19:55:01 IST" duration-ms="344733" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to click: [Located by By.chained({By.xpath: //android.widget.TextView[@text="Add New Address"]})]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to click: [Located by By.chained({By.xpath: //android.widget.TextView[@text="Add New Address"]})]
at org.testng.Assert.fail(Assert.java:111)
at CommonUtility.CommonAppium.waitForWebElementToBeClickable(CommonAppium.java:143)
at Pages.ResidentHomePage.addingNewServiceAddress(ResidentHomePage.java:311)
at TestCases.LoginTest.TC01_Bathroom_Cleaning_Flow(LoginTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Bathroom_Cleaning_Flow -->
        <test-method signature="TC02_Verifying_CancelationPolicy()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:55:02 IST" name="TC02_Verifying_CancelationPolicy" finished-at="2024-02-04T19:55:02 IST" depends-on-methods="TestCases.LoginTest.TC01_Bathroom_Cleaning_Flow" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCases.LoginTest.TC02_Verifying_CancelationPolicy() on instance TestCases.LoginTest@5f2606b depends on not successfully finished methods 
[TestCases.LoginTest.TC01_Bathroom_Cleaning_Flow() on instance TestCases.LoginTest@5f2606b]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCases.LoginTest.TC02_Verifying_CancelationPolicy() on instance TestCases.LoginTest@5f2606b depends on not successfully finished methods 
[TestCases.LoginTest.TC01_Bathroom_Cleaning_Flow() on instance TestCases.LoginTest@5f2606b]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_Verifying_CancelationPolicy -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:55:02 IST" name="quitDriver" finished-at="2024-02-04T19:55:02 IST" duration-ms="527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="quitServer()[pri:0, instance:TestCases.LoginTest@5f2606b]" started-at="2024-02-04T19:55:02 IST" name="quitServer" finished-at="2024-02-04T19:55:02 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitServer -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
